import { useState } from 'react'
import { Brain, HeartHandshake, Menu, X, ArrowRight, Sparkles, Gamepad2, Mic, BellRing, MapPin, WifiOff, Languages, ShieldCheck, UsersRound, Activity, ChevronRight, Home, Check, Stethoscope, Clock3, Phone, Route, Pill, Heart, Lightbulb } from 'lucide-react'
import heroImage from './assets/mindcare-hero.png'

const nav = ['Home', 'Features', 'How It Works', 'About', 'Contact']
const challenges = [
  ['Memory loss', Brain, 'Remembering familiar people, places and moments.'], ['Confusion & anxiety', Sparkles, 'Feeling disoriented during everyday routines.'], ['Medicine schedules', Pill, 'Keeping track of important medications.'], ['Daily activities', Clock3, 'Managing appointments and simple tasks.'], ['Caregiver visibility', UsersRound, 'Staying connected from a distance.'], ['Limited connectivity', WifiOff, 'Accessing support in remote locations.'], ['Finding the way home', Route, 'Getting safely back to a saved location.']
]
const features = [
  ['Cognitive Games', Gamepad2, 'Thoughtful activities for memory, focus, recognition and attention.'], ['AI Personalization', Sparkles, 'Activities adapt gently based on progress and engagement.'], ['Voice Assistance', Mic, 'Simple, voice-enabled guidance made for everyday comfort.'], ['Smart Reminders', BellRing, 'Helpful prompts for medicines, hydration and appointments.'], ['Caregiver Monitoring', Activity, 'A clear view of activity, mood and cognitive engagement.'], ['Safe Return Home', MapPin, 'Offline-assisted guidance to a saved home location.'], ['Offline Support', WifiOff, 'Important assistance remains accessible with limited connectivity.'], ['Multilingual Support', Languages, 'English, Hindi and future North-Eastern languages.']
]
const future = [['Memory Games', Gamepad2],['Cognitive Analytics', Activity],['AI Voice Assistant', Mic],['Medicine Reminders', Pill],['Caregiver Dashboard', UsersRound],['Offline Safe Navigation', MapPin],['Offline Sync', WifiOff],['Regional Languages', Languages],['Emergency Alerts', BellRing]]

function Button({ children, kind='primary', className='', ...props }) { return <button className={`btn ${kind === 'primary' ? 'btn-primary' : 'btn-secondary'} ${className}`} {...props}>{children}</button> }
function Logo() { return <a href="#home" className="logo"><span className="logo-mark"><Brain size={22}/><Heart size={10} fill="currentColor"/></span><span>MindCare <b>NER</b></span></a> }
function Navbar({ openLogin }) { const [open, setOpen] = useState(false); return <header className="navbar"><div className="container nav-inner"><Logo/><nav className={open ? 'nav-links show' : 'nav-links'}>{nav.map(x => <a key={x} href={`#${x.toLowerCase().replaceAll(' ', '-')}`} onClick={() => setOpen(false)}>{x}</a>)}<div className="mobile-actions"><Button kind="secondary" onClick={() => openLogin('Patient')}>Patient Login</Button><Button onClick={() => openLogin('Caregiver')}>Caregiver Login</Button></div></nav><div className="desktop-actions"><button className="text-button" onClick={() => openLogin('Patient')}>Patient Login</button><Button onClick={() => openLogin('Caregiver')}>Caregiver Login</Button></div><button className="menu" aria-label="Toggle navigation" onClick={() => setOpen(!open)}>{open ? <X/>:<Menu/>}</button></div></header> }
function Hero({ openLogin }) { return <section id="home" className="hero"><div className="hero-orb orb-one"/><div className="hero-orb orb-two"/><div className="container hero-grid"><div className="hero-copy"><div className="eyebrow"><span className="pulse"/> Made with care for North East India</div><h1>Empowering elderly minds with <em>AI-powered</em> cognitive care.</h1><p>An intelligent cognitive assistance and safety platform designed to support elderly individuals with dementia through personalized brain activities, daily assistance and caregiver support.</p><div className="hero-actions"><Button onClick={() => openLogin('Caregiver')}>Get started <ArrowRight size={18}/></Button><Button kind="secondary" onClick={() => document.querySelector('#features').scrollIntoView({behavior:'smooth'})}>Explore features</Button></div><div className="trust-row"><span><ShieldCheck/> Safe & accessible</span><span><HeartHandshake/> Built for care</span></div></div><div className="hero-art"><div className="art-glow"/><img src={heroImage} alt="An elderly woman using a tablet with a caregiver and AI cognitive support"/><div className="float-card activity-card"><span className="icon-bubble violet"><Activity size={18}/></span><div><small>Today’s activity</small><strong>Great progress!</strong></div></div><div className="float-card safe-card"><span className="icon-bubble coral"><Heart size={18} fill="currentColor"/></span><div><small>Care circle</small><strong>Connected</strong></div></div></div></div></section> }
function SectionTitle({ eyebrow, title, text, center=true }) { return <div className={`section-title ${center ? 'center':''}`}><span className="eyebrow">{eyebrow}</span><h2>{title}</h2>{text && <p>{text}</p>}</div> }
function Challenges() { return <section className="section soft-section"><div className="container"><SectionTitle eyebrow="Understanding the need" title="The challenge" text="Elderly individuals in remote and rural areas often have limited access to specialized cognitive care and continuous healthcare support."/><div className="challenge-grid">{challenges.map(([title,Icon,txt])=><article className="challenge-card" key={title}><span className="icon-bubble amber"><Icon size={22}/></span><h3>{title}</h3><p>{txt}</p></article>)}</div></div></section> }
function Features() { return <section className="section" id="features"><div className="container"><SectionTitle eyebrow="A connected care ecosystem" title="One platform. Complete cognitive care." text="Gentle, practical support that brings patients, caregivers and healthcare workers closer together."/><div className="feature-grid">{features.map(([title,Icon,text],i)=><article className="feature-card" key={title}><span className={`icon-bubble ${['blue','violet','teal','coral'][i%4]}`}><Icon size={21}/></span><h3>{title}</h3><p>{text}</p><span className="feature-arrow"><ArrowRight size={17}/></span></article>)}</div></div></section> }
function HowItWorks() { const steps=[['01','Create a Patient Profile','A caregiver or health worker creates a simple profile.'],['02','Daily Cognitive Engagement','The elder enjoys clear activities at their own pace.'],['03','AI Learns & Adapts','The system adjusts activities based on engagement.'],['04','Caregivers Stay Connected','See activity, reminders and trends in one place.']]; return <section id="how-it-works" className="section how-section"><div className="container"><SectionTitle eyebrow="Simple from the start" title="How MindCare works"/><div className="steps">{steps.map(([no,title,text],i)=><div className="step" key={no}><div className="step-number">{no}</div>{i<3&&<div className="step-line"><ChevronRight/></div>}<h3>{title}</h3><p>{text}</p></div>)}</div></div></section> }
function SafeHome() { return <section className="section" id="safe-home"><div className="container safe-home"><div className="home-visual"><div className="map-grid"/><div className="map-road road-a"/><div className="map-road road-b"/><div className="pin pin-home"><Home size={21} fill="currentColor"/></div><div className="pin pin-user"><span/></div><div className="home-button"><MapPin size={20}/><span>TAKE ME<br/>HOME</span></div><div className="location-note"><span className="icon-bubble teal"><Route size={17}/></span><div><small>Saved location</small><strong>Home • 1.2 km away</strong></div></div></div><div className="safe-copy"><span className="eyebrow"><MapPin size={14}/> Future safety feature</span><h2>Lost or confused? <em>Let us help you get home.</em></h2><p>Offline-assisted navigation will use pre-downloaded map information and GPS location to guide an elderly user toward their saved home location.</p><div className="safe-list">{['Large emergency-friendly button','Simple voice-guided directions','GPS location assistance','Option to contact caregivers'].map(x=><span key={x}><Check size={16}/>{x}</span>)}</div><p className="disclaimer"><Lightbulb size={16}/> This feature assists users and caregivers; it does not replace supervision or emergency services.</p></div></div></section> }
function Benefits() { const groups=[['For Elderly Users',Heart,['Simple & accessible technology','Cognitive engagement','Daily routine assistance','Greater independence']],['For Caregivers',UsersRound,['Activity monitoring','Reminder tracking','Cognitive performance insights','Peace of mind']],['For Healthcare Workers',Stethoscope,['Patient activity insights','Cognitive engagement trends','Remote accessibility','Support for rural communities']]]; return <section className="section soft-section"><div className="container"><SectionTitle eyebrow="Care that reaches everyone" title="Designed for independence and peace of mind"/><div className="benefit-grid">{groups.map(([title,Icon,items],i)=><article className={`benefit-card b-${i}`} key={title}><span className="icon-bubble"><Icon size={22}/></span><h3>{title}</h3>{items.map(x=><p key={x}><Check size={16}/>{x}</p>)}</article>)}</div></div></section> }
function Future() { return <section className="section" id="about"><div className="container future-wrap"><div><SectionTitle center={false} eyebrow="Growing with every need" title="A platform designed for what comes next." text="MindCare NER begins with a thoughtful foundation and grows alongside the people it serves."/><Button kind="secondary">Learn more <ArrowRight size={17}/></Button></div><div className="future-grid">{future.map(([name,Icon])=><div className="future-card" key={name}><span className="coming">Coming soon</span><Icon size={22}/><span>{name}</span></div>)}</div></div></section> }
function CTA({ openLogin }) { return <section id="contact" className="cta"><div className="container cta-inner"><div><span className="eyebrow">MindCare NER</span><h2>Building a safer and healthier future for elderly care.</h2><p>Technology can help elders stay mentally engaged, connected, independent and safe.</p></div><div className="cta-actions"><Button onClick={() => openLogin('Caregiver')}>Get started <ArrowRight size={18}/></Button><Button kind="secondary">Learn more</Button></div></div></section> }
function Footer(){return <footer><div className="container footer-top"><div><Logo/><p>AI-powered cognitive care and safety platform.</p></div><div className="footer-links">{nav.slice(0,4).map(x=><a href={`#${x.toLowerCase().replaceAll(' ','-')}`} key={x}>{x}</a>)}</div></div><div className="container footer-bottom"><p>© 2026 MindCare NER. Designed with care for North East India.</p><p>MindCare supports cognitive engagement and elderly care. It does not replace professional medical diagnosis or emergency services.</p></div></footer>}
function LoginModal({type,onClose}){ if(!type)return null;return <div className="modal-backdrop" onClick={onClose}><div className="modal" onClick={e=>e.stopPropagation()}><button className="modal-x" onClick={onClose}><X/></button><span className="icon-bubble blue"><HeartHandshake/></span><h2>{type} portal</h2><p>The {type.toLowerCase()} portal is being prepared for the next phase of MindCare NER.</p><Button onClick={onClose}>Continue exploring</Button></div></div>}
export default function App(){const [login,setLogin]=useState(null);return <><Navbar openLogin={setLogin}/><main><Hero openLogin={setLogin}/><Challenges/><Features/><HowItWorks/><SafeHome/><Benefits/><Future/><CTA openLogin={setLogin}/></main><Footer/><LoginModal type={login} onClose={()=>setLogin(null)}/></>}
